name: cypher
description: "App to test encryption in texts"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0-127.0.dev

dependencies:
  flutter:
    sdk: flutter
  encrypt: ^5.0.3
  basic_utils: ^5.7.0
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/one-key.jpg
    - assets/images/shield-blue.jpg
    - assets/images/shield-pink.jpg
    - assets/images/two-keys.jpg

  fonts:
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
